### PR TITLE
Add Several Camera Functions

### PR DESCRIPTION
**Pull request by yurividal**
This PR adds the following camera control functions:
xCommand Camera Ramp (Move Up/Down/Left/Right)
xCommand Camera TriggerAutofocus
xCommand Camera Preset Activate
xCommand Camera Preset Remove
xCommand Camera Preset Store
Zoom In/Out
Focus Far/Near

It also adds the possibility to set a default camera ID on the settings page, to make it easier for the user in case their camera id  is not "1".

Tested on Cisco C90, with PrecisionHD 1080P 12X Camera.
C90 Running TC7.3.20.caa4cf9

The requests for this came initially from [here](https://github.com/bitfocus/companion-module-requests/issues/388)

### CODE REVIEW

**Comment by nottooloud** [comment]
Would it be possible to have multiple IDs, for multiple cameras? A typical concert streaming setup is 3 or 4 cameras. The codec can control 7.

**Comment by nottooloud** [comment]
Ah, got it, there is a field for camera ID in the action. All works great so far.
Could use diagonals. Up and Left, etc. 
A 3x3 Pan Tilt grid with Trigger Autofocus in the center is useful.

**Comment by yurividal** [comment]
The camera doesn't support direct diagonal command. But, you should be able to set your button to send "up" and then "left" some ms latter. Not sure how the system would behave. Maybe it would only execute the "left" after the "up" is done? Idk, would need to test, but unfortunately I've left the office already.

**Comment by nottooloud** [comment]
I have chained commands in the web implementation I sent you. Works.
This works as is, though.
Forgot we need Focus Auto/Manual for when you don't want to pay attention to it.

Amazing work today. I thank you, sir.

**Comment by nottooloud** [comment]
Oh, I see what you were saying. Just add an up to the left, with a delay. Yes, that works.

**Comment by yurividal** [comment]
The auto/manual focus is an xConfiguration command and not an xCommand command, so it would require more modifications to the code. I should be able to take a look and test it sometime next week. But, for now, if you use the manual focus it should stick to whatever you focus on. And if you need to autofocus, you can just use the autofocus trigger that i implemented and it triggers it once. (Maybe add it as a second action to your move buttons?)

**Comment by nottooloud** [comment]
The manual focus turns out to be too course to really be usable. That’’s going to need high res MIDI or something. Triggering autofocus works. This is excellent.

Dan

**Pull request merged**
